DPI = 600
SQUARE_FIG_SIZE = (8, 8)
RECTANGLE_FIG_SIZE = (15, 6)

DEFAULT_SIGNAL_COLOR = 'blue'

TITLE_FONT_SIZE = 16
AXIS_LABEL_FONT_SIZE = 14
AXIS_TICKS_FONT_SIZE = 12
ANNOTATION_FONT_SZIE = 12
LEGEND_FONT_SIZE = 12
